### ISSUE TITLE
simple injector issue

### ISSUE THREAD

**Issue by Zooted711** [Saya-de/Dead-by-Daylight-Unlocking-Utils#2]
I did everything how you said in the steps and pasted the bhvr cookie into the injector but when i go to the next screen and press inject profile I get an error "the remote server returned an error: (401) Unauthorized"

**Comment by Saya-de** [comment]
this error 401 only occurs when you send an invalid request. In this case you pasted the wrong cookie or you forgot to have dbd open while injecting. Please remember that the bhvr Cookie can change when you restart your game etc
