### ISSUE TITLE
Can't find the URL

### ISSUE THREAD

**Issue by Rostile** [Saya-de/Dead-by-Daylight-Unlocking-Utils#4]
I did everything like u, but the basic setup didnt work, I didn't get all of the characters and the URL /apiv1/owned-products/get-update-entitlements doesn't show up in the list on the left, so maybe dbd fixed it?? (I'm pretty sure I didn't make a mistake.)

**Comment by Zooted711** [comment]
this is outdated as of right now

**Comment by Saya-de** [comment]
SSL-Bypass is patched. Maybe there is going to be a new one in the future.
